'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50215.44
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

<Assembly: Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope:="member", Target:="My.Resources.Resources.get_ResourceManager():System.Resources.ResourceManager"),  _
 Assembly: Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope:="member", Target:="My.Resources.Resources.get_Culture():System.Globalization.CultureInfo"),  _
 Assembly: Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope:="member", Target:="My.Resources.Resources.set_Culture(System.Globalization.CultureInfo):Void")> 

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleName()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If (resourceMan Is Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CardGame.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property backGreen() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("backGreen", resourceCulture),System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Background() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("Background", resourceCulture),System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BorderPlaceYourBetBottom() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("BorderPlaceYourBetBottom", resourceCulture),System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BorderPlaceYourBetTop() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("BorderPlaceYourBetTop", resourceCulture),System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ButtonRound() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("ButtonRound", resourceCulture),System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ButtonRoundRollOver() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("ButtonRoundRollOver", resourceCulture),System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ButtonSquare() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("ButtonSquare", resourceCulture),System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cardSkin() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("cardSkin", resourceCulture),System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property coin1() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("coin1", resourceCulture),System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property coin2() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("coin2", resourceCulture),System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property coin3() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("coin3", resourceCulture),System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property coin4() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("coin4", resourceCulture),System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FrameBlue() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("FrameBlue", resourceCulture),System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FrameBrightRed() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("FrameBrightRed", resourceCulture),System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FrameGreen() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("FrameGreen", resourceCulture),System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FrameOrange() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("FrameOrange", resourceCulture),System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FramePink() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("FramePink", resourceCulture),System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FrameRed() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("FrameRed", resourceCulture),System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FrameTextField1() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("FrameTextField1", resourceCulture),System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FrameTextField2() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("FrameTextField2", resourceCulture),System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FrameTextField3() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("FrameTextField3", resourceCulture),System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FrameTextField4() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("FrameTextField4", resourceCulture),System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FrameTextField5() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("FrameTextField5", resourceCulture),System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SplashPage() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("SplashPage", resourceCulture),System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property StartMenuIcon() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("StartMenuIcon", resourceCulture),System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TemplateIcon() As System.Drawing.Icon
            Get
                Return CType(ResourceManager.GetObject("TemplateIcon", resourceCulture),System.Drawing.Icon)
            End Get
        End Property
    End Module
End Namespace
